### ISSUE TITLE
@mout.debug_log on line 190 in volumes.py shits the bed when I load MolParse

### ISSUE THREAD

**Issue by LouieSlocombe** [mwinokan/MolParse#8]

**Comment by mwinokan** [comment]
Did you download from PyPI or source?

**Comment by LouieSlocombe** [comment]
pip install git+https://github.com/mwinokan/MolParse.git

**Comment by LouieSlocombe** [comment]
(things work if I just comment it out)

**Comment by mwinokan** [comment]
Did you update MPyTools? That's where the `mout` module lives. It's on [PyPI](https://pypi.org/project/MPyTools/)

(Otherwise quick fix for now is to just not import that `monte` submodule if you don't need it. Comment out line 187 here in [__init__.py](https://github.com/mwinokan/MolParse/blob/master/molparse/__init__.py))

**Comment by LouieSlocombe** [comment]
re-installed on PyPI seems to fix itself...

**Comment by mwinokan** [comment]
Seems to me that MPyTools was out of date, I've updated the README.md
